### ISSUE TITLE
This bad boy is missing a README.md file

### ISSUE THREAD

**Issue by camratchford** [keethesh/UdemyCourseGrabber#1]
I noticed your post on reddit with a user saying they didn't know how to run it, this might help other novices to use your very handy script. Plus it's a good opurtunity to give people a good first impression of your project.

Cheers

**Comment by RHQ-Rusty** [comment]
@camratchford 
I'm here from Reddit as well! I'm experienced in Python, and some starting reference points I can give you are as follows:

- Once downloaded, rename `geckodriver` to `geckodriver.exe`
- Open the CMD in the directory you extracted/cloned to
- Type `pip install -r requirements`
- Type `py main.py`

With that being said, however, I am still encountering runtime errors whilst performing the above steps. I would recommend waiting for @keethesh to come out with an official `README.md` and inform us of the specific use of the program.

**Comment by keethesh** [comment]
Done! Thanks for the advice!
