### ISSUE TITLE
handle for download_link being NoneType

### ISSUE THREAD

**Issue by HomunculusK** [keethesh/UdemyCourseGrabber#11]
File "main.py", line 97, in <module>
    interactive()
  File "main.py", line 63, in interactive
    course_info = get_sites(course_name)
  File "C:\Users\****\UdemyCourseGrabber\functions.py", line 73, in get_sites
    if "magnet" in download_link:
TypeError: argument of type 'NoneType' is not iterable

tried replacing

`if len(download_link) == 0:
continue`
with
 `            if len(download_link) == 0 or download_link is None:
                continue`

put that just makes 100 more exceptions I'm too lazy to follow through
to replicate search for "Python for Finance: Investment Fundamentals & Data Analytics"

**Comment by keethesh** [comment]
Fixed!
