### ISSUE TITLE
Suggestion: TQDM Progress-bars w/ Detailed Search Log

### ISSUE THREAD

**Issue by RHQ-Rusty** [keethesh/UdemyCourseGrabber#5]
Implementation of TQDM to use a progress bar whilst searching sources, maybe an additional print for each site it is searching to know which part of the repository the program is at in terms of scans for the matching Udemy course.

**Comment by keethesh** [comment]
That's a good idea, I'll try implementing that in the near future.

**Comment by keethesh** [comment]
Pushed a commit with a progressbar to the dev branch

**Comment by keethesh** [comment]
Pushed to master
